[build]
  command = "npm run build"
  publish = "dist"


[context.production]
  environment = { NODE_VERSION = "12.18.0" }


[[plugins]]
  package = "@netlify/plugin-local-install-core"

# Config for the Netlify Build Plugin: netlify-plugin-add-instagram
[[plugins]]
  package = "./plugins/netlify-plugin-cloudinaryfy"

  [plugins.inputs]

    cloudinaryCloudName = "jlengstorf"

